name: payment-service-dev-app-v1
namespace: payment-service-dev
project: payment-service-dev
imageName: nginx
imageTag: "1.27"
replicas: 1
config:
  APP_MESSAGE: "hello payment dev"
  APP_COLOR: "blue"
  FEATURE_X_ENABLED: "true"
sealedSecret:
  name: app-secret
  encryptedData:
    API_KEY: "JKFJSDKJFSKLDJFLKSDJFKLDSJFKLDSJFKLSDJFLKSDJFKLSDJFE"
    DB_URL: "postgres://user:password@localhost:5432/paymentdb"
