name: payment-service-dev-app-v1
namespace: payment-service-dev
project: payment-service-dev
imageName: nginx
imageTag: "1.27"
replicas: 1
config:
  APP_MESSAGE: "hello payment dev"
  APP_COLOR: "blue"
  FEATURE_X_ENABLED: "true"
sealedSecret:
  encryptedData:
    API_KEY: "AgBXt9Qjti9LCCtCl96BLkY5zMJODAHhJJqkMsLJqJS4M3OR7oOpAeN+dP0gBX50StvlLOKg0luHlWajh4TI5geXlLtAomuUrPsA9SbbPLNPQSBsAr8ncAGZXtOvejW6dF5V5MnzGy2ybnMgQhgyrFYjSo+xqXITw3f9+JWKxcqrwF7dtyD0RsjNP/0YYCK7yRbBUzNVy5ZHaydWxlVWIFbEiteAt19iC+fPbB72zvSd972GOhOmDmmq0beuLCjUVVNHCKvYrfgqR4lVLF9bjKKW0KrOii7+Yv5VXEv5ZwJTojHxeIfbWZl9h54fvoklotPcxX2MsnXtAAbVZPfbt9FZ2Wh/IZ/xZhq1hhrO3fhP1zD/pr2O1SjgK/5wQ3X/l5T3/omxV9YaJfOC8f0/ne6o5Cbx/DGgUwJ/U9zMwvQxD8YiJz7pe5BY38Xpuw6L8ka0KZ4N+L7G9BX4570r8oQTCl7GwRootw8Gvr1JOYRmLtq0FFN54qe3K3APyzoYM1yk6kpTtI3dZ/ffEd5Vve1u3lg4EpOqxSiik9UHzjYE3btRjWZZX5C7uB1vpS15+38KnGqIG6UprKn2m5uox4+bz3Ii/FOlhX5oqASF7Qa9rYP04Sg1CXpf29Em5wHNW4kniGguSptcVSX79XTbdHP9s5x2feEAU6OAygmRuu2Cip1Y1oCVih83YdNPF69VIg84mU/8rk9ZnA=="
    DB_URL: "AgBkH5Gt2ygBPK7V2NVhZLlyYUMIqizjyz0V9t7mcnvB9joLhen9JXvIdwE+mfNzPbtkmmDeFyH9K1u0uU5Fkzwj7n/wuMo+h3y+UR9MahX+iIM1OuY62Ly/TrlynE1+onn7eZ8gMLnWQ0sXsk2cIXhSdPyQMFlqejpmQVL6EjsMglYVm+vuDMZauheRE8/5qAY3Z8bio0SC5s7JOYS1Kzcf7B/yQXLpOdi6VltJKDxK3HSMNHbnhv2LWdjE6Nwl8HkNpI3jfbIkZF/sUkYu1d+Cmz4Lms0Ef0qusroLB4jTlv+Cl+RAltSx34GnddlJ/h6wuZ5utRuZRnZmLlGpo/o47B2NbRD2/RFcTRJ50f+qAlyYFZL6Jbm0ZxkkKSbbY5yYNUTntcGPp7YQ/luO05ZmcSd4CnnR+I3VvnCjnGR95yS8H6lEX7RBBbuGCeQfODHIgbWLn0ZDmUObmM6oeL/+eWxLWFWYEfvTLHYxKzqwwKBX10arG15Oo3EE1CG3jZDuhUg64cMCV2m6sGxQdJuetSLeXsmUFV7DoabvOAhaJm623wxIEWnamVK6/xiQtH9NMv6po4/RdylJtqkGS1+byrD0Mmnm19LM+EidbEOImmyxxcDemUepy1dJpb4fz4N6aNLj27g0MCzaAIAB7+8AN87gzAin6PV8A+ymmdfcRqQ/QKdzxsCKF25F3WvcZOhUyRBc0VZOu/zOFnggAWjqKW3GjTPq6qxrA9dm3uoX2zERjxx4NeQA"
