name: payment-service-dev-app-v1
namespace: payment-service-dev
project: payment-service-dev
imageName: nginx
imageTag: "1.27"
replicas: 1
config:
  APP_MESSAGE: "hello payment dev"
  APP_COLOR: "blue"
  FEATURE_X_ENABLED: "true"
sealedSecret:
  name: app-secret
  encryptedData:
    API_KEY: "AgCP6Oy1hvPzWnIYHzm7Yt226WWv/Bu9dwDUYyK2cXV0YULD1Z4swduuh8ZeN9c6HE5VJaFuP0wyg7YiwWKKLWeA45A+amba/S3OvslDG9KmKkZ1d3K4xu+6Nvxu0PFbJ6tSR/57qk724ed2gkpFezOO7uRDrBrF/qg+FkNvqa4JRF9fWLCwfbQ4qnb9ebz3qWhYPQL7/sJb133JqhZRfqOQl4TxTKW44QiBOgCA6nvjkeYhsyuY8lEsNbN1cQevm8VHf9zPnbQ2C81DSFsleFj7tSO57O8Lf/d6MyzvpPF+veXA6unncheCLid9hCcQ1d+wdXSGYKuJRCkGDNw16E74FZvlXmCunLHxN8nMv3XDPPCT7JU/bQfBjNF4AvzL7UJ3ldHax2t4jB5ZesWipsUs174PE3NVPw6cF2WlIz8clt3nnvhxgaXJ9uLwLXCIClZtsZR5t9BZ6nd34FxMoJD26AWp6xw1yB+STJc2QnJmjTDZ9oJeMJiL+cz6vdoqmsF8qsCycDXbps0umDOGx3x+Oe8KVix0vLEm0A1M24IEIJZdvwoZ+xqAlFtjE7XX4StVapVk18GF7FFCutO4tidQ28CkfuKx+1Pq/gEO03pIjyk3oGW9YPw+1tEovVvpY54oKxg3vLnkZ4vL0oIUlIjIM6ngf5qTxXCRLHaUL3R+gdeXQBxrlAkx1l69XIHf36gKSk6GZWwMSg=="
    DB_URL: "AgASu3yPKDJTkE1Ug1v6lPqipmo0PPTiCWalXtDWWxwI7oH0KQ9yN+vVFoDqvX/9AcYWy17+ELcUvkyhi3/cJVkJl8hVv/BaNWBfjWsQzX5E8hcxHgW13j7S5dSaA4UT2GK0Sl0TLAuOtj6UGh5EN40PJQ1mTX6w91KJNQaDdIp1EWbKg29K7EB3KSXJRl4ZtshCzNKLGDLtqHtBzIVyKU4SmB+JXGcpdJh/U/lyiwK63IabcWBRrEkIEImSi/SNrLMqWgoaKav+UzGDXqHmp2g57h07VGtrNVTJXObAwu0TA+AUjTSQSqxzgIN+JUSqWnKxj+mvk750YJ3pL8ofzaKwBZTETfg2YEVIPSUko+tguHagSFNv54z168vc5mjgMH+gG2lG4LtSyktA7Os4jHRbS5VgZkS2rboWOIhFKq0q5zImmVPpxIjANBDiICihYUzZTQwqTWoWXqDgf+VmfLLvPv8IilkdHMYBLokWXbBO9C4BDUJ2Jl+NCdllMOAdKK3EvSSDQgZfcBg2udd7RtNYEYe13suAqOOZa+jL2hLpC1kuIFG9swwvgOS8MwiaAIScKS268LKT4aFuJjT4+qBrVn6YaXuNccBL/ZoQW9BreTh/hfBzldX+mVuzpEuOxvAgzABPEK8RRYJDwIY75V81nrS6Pp1910kld8nUv2xk2jpQe77inV7tQf3GchdYIHKxbctSuMbXhQdZp3eFr/RS+n2NLHdKYsQkP4mjbzL73/3XDRzu9q0c"
